[tools]
fd = "latest"
ripgrep = "latest"
jq = "latest"
fzf = "latest"
zoxide = "latest"
yazi = "latest"
eza = "latest"
bat = "latest"
lazygit = "latest"
ast-grep = "latest"
starship = "latest"
go = "latest"
node = "lts"
bun = "latest"
pnpm = "latest"

[settings]
auto_install = true
not_found_auto_install = true
yes = true
jobs = 4
raw = false
activate_aggressive = true

[env]
PAGER = "bat --plain"
